version: "3.8"

services:
  go-app:
    build: ./
    command: ./wait-for-postgres.sh db ./go-app
    ports:
    - 8080:8080
    depends_on:
    - db
    environment:
    - DB_PASSWORD=hbdtkjy2012

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=hbdtkjy2012
    ports:
    - 5436:5432