// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SegGetter is an autogenerated mock type for the SegGetter type
type SegGetter struct {
	mock.Mock
}

// GetClientSeg provides a mock function with given fields: id
func (_m *SegGetter) GetClientSeg(id int) ([]string, error) {
	ret := _m.Called(id)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) []string); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSegGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewSegGetter creates a new instance of SegGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSegGetter(t mockConstructorTestingTNewSegGetter) *SegGetter {
	mock := &SegGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
