// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SegDeleter is an autogenerated mock type for the SegDeleter type
type SegDeleter struct {
	mock.Mock
}

// DeleteSeg provides a mock function with given fields: name
func (_m *SegDeleter) DeleteSeg(name string) (int64, error) {
	ret := _m.Called(name)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSegDeleter interface {
	mock.TestingT
	Cleanup(func())
}

// NewSegDeleter creates a new instance of SegDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSegDeleter(t mockConstructorTestingTNewSegDeleter) *SegDeleter {
	mock := &SegDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
